version: '3.8'
services:
  flask_app:
    image: python:3.9-slim
    container_name: qrcode_generator
    working_dir: /app
    ports:
      - "5008:5008"
    volumes:
      - ./app:/app
      - ./html:/html
      - ./generated_qrcodes:/app/generated_qrcodes
    command: >
      sh -c "pip install -r requirements.txt && python app.py"
